#ifndef _BEMINTREG3D_
#define _BEMINTREG3D_
void bemintreg3d(const double* const Nod, const unsigned int& nNod, 
                 const double* const Elt, const unsigned int& iElt, const unsigned int& nElt,
                 const unsigned int* const  TypeID, const unsigned int* const nKeyOpt, 
                 const char* const TypeName[], const char* const TypeKeyOpts[], 
                 const unsigned int& nEltType, const double* const Coll, 
                 const unsigned int& nColl, const unsigned int* const RegularColl, 
                 const unsigned int* const EltCollIndex, const unsigned int& nDof, 
                 const void* const* const greenPtr, const unsigned int& nGrSet, 
                 const bool& ugCmplx, const bool& tgCmplx, 
                 const bool& tg0Cmplx, double* const URe, double* const UIm, 
                 double* const TRe, double* const TIm, const bool UmatOut,const bool TmatOut,
				 const double* const s,
				 const unsigned int& ms,
            	 const unsigned int& ns,
				 // const unsigned int* const scolli,
 				 const unsigned int* const scompi,
				 const unsigned int* const uniquescolli,
				 const unsigned int* const Nuniquescolli,
				 const unsigned int* const nuniquescolli,
				 const unsigned int* const uniquescolliind,
				 const unsigned int* const scollj,
				 const unsigned int* const scompj,
				 // const unsigned int* const uniquescollj,
				 // const unsigned int* const Nuniquescollj,
				 // const unsigned int* const nuniquescollj,
				 // const unsigned int* const uniquescolljind,
				 const bool* const InListuniquecollj,
				 const unsigned int* const inddiag,
				 const bool& ondiag);
#endif
